name: Review Bot

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Important for commenting on PRs
    steps:
      - uses: actions/checkout@v3
      - name: Run Review Bot
        uses: aleksbanks/review-bot-action@v1.8
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
